# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-03 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='prof_img/default.png', null=True, upload_to='prof_img'),
        ),
    ]
