# Generated by Django 2.2.3 on 2019-07-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190703_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='prof_img/default.jpg', null=True, upload_to='prof_img'),
        ),
    ]
