# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-06 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190706_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
