# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-20 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190720_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='prof_img'),
        ),
    ]
