# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-20 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20190720_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='prof_img/default.jpg', null=True, upload_to='prof_img'),
        ),
    ]
