# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-20 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20190720_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profiles/default.jpg', null=True, upload_to='profiles'),
        ),
    ]
