# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-29 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20190729_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badges',
            name='badge_type',
        ),
        migrations.RemoveField(
            model_name='badges',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_bugs',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_comments',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_features',
        ),
        migrations.DeleteModel(
            name='Badges',
        ),
        migrations.DeleteModel(
            name='BadgeType',
        ),
    ]
