# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-07 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_ticket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('Bug Report', 'Bug Report'), ('Feature Request', 'Feature Request')], max_length=20, null=True),
        ),
    ]
