# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-07 13:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20190707_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='raised_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raised_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
