# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-09 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_remove_ticket_ticket_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
