# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-10 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_ticket_ticket_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=2000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('To-Do (Not Started)', 'To-Do (Not Started)'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='To-Do (Not Started)', max_length=20),
        ),
        migrations.AddField(
            model_name='comments',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.Ticket'),
        ),
    ]
