# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-12 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_bugupvote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bugupvote',
            old_name='author',
            new_name='user',
        ),
    ]
