# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-13 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_auto_20190712_1800'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BugUpvote',
            new_name='Upvote',
        ),
    ]
