# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-17 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_auto_20190713_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
