# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-20 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_ticket_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_status', models.CharField(choices=[('To-Do (Not Started)', 'To-Do (Not Started)'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.ForeignKey(default='To-Do (Not Started)', on_delete=django.db.models.deletion.CASCADE, to='tickets.TicketStatus'),
        ),
    ]
