# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-20 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_auto_20190720_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='tickets.TicketStatus'),
        ),
    ]
