# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-24 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_auto_20190720_1027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('-last_updated',)},
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='ticket_type',
            field=models.CharField(choices=[('Bug Report', 'Bug Report'), ('Feature Request', 'Feature Request')], max_length=15),
        ),
    ]
