language: python
python:
    - "3.6"
before_install:
    - cd src
    - sudo apt-get install libgnutls28-dev
install: "pip install -r requirements.txt"
script:
    - SECRET_KEY="TestingKey" python manage.py test